#!/bin/bash

export LC_ALL=C
./mk-list -d myfinal -v1 english british 50 | grep -v "'" | grep -v '[^A-Za-z]' | awk 'length($0) >=2 && length($0) <=4' >words24.txt
awk '{print tolower($0)}' <words24.txt >lowered24.txt
sort <lowered24.txt >sorted24.txt
uniq <sorted24.txt >uniq24.txt
